### ISSUE TITLE
Incorrect permissions set

### ISSUE THREAD

**Issue by miketheman** [twitter/thrift_client#32]
In versions 0.5.0, 0.6.0, the connection client permissions were world readable, so a project could include the gem correctly.

This is preventing users not members of the rvm group or root from reading the connection.rb and files.

```bash
$ ll /usr/local/rvm/gems/ruby-1.8.7-p352/gems/thrift_client-0.6.3/lib/thrift_client
total 36
-rw-r--r-- 1 root rvm 5274 Aug 12 00:14 abstract_thrift_client.rb
drwxr-sr-x 2 root rvm 4096 Aug 12 00:14 connection
-rw-r----- 1 root rvm  165 Aug 12 00:14 connection.rb
-rw-r----- 1 root rvm 3050 Aug 12 00:14 event_machine.rb
-rw-r----- 1 root rvm 8225 Aug 12 00:14 simple.rb
-rw-r--r-- 1 root rvm  565 Aug 12 00:14 thrift.rb

$ ll /usr/local/rvm/gems/ruby-1.8.7-p352/gems/thrift_client-0.5.0/lib/thrift_client
total 36
-rw-r--r-- 1 root rvm 4868 Aug 12 00:12 abstract_thrift_client.rb
drwxr-sr-x 2 root rvm 4096 Aug 12 00:12 connection
-rw-r--r-- 1 root rvm  165 Aug 12 00:12 connection.rb
-rw-r--r-- 1 root rvm 3050 Aug 12 00:12 event_machine.rb
-rw-r--r-- 1 root rvm 8225 Aug 12 00:12 simple.rb
-rw-r--r-- 1 root rvm  315 Aug 12 00:12 thrift.rb
```

**Comment by danzilio** [comment]
I'm also seeing this in 0.9.3

**Comment by miketheman** [comment]
I can also confirm that this problem persists.
This likely stems from build-time umask permissions, and rubygems has been updated to handle certain cases.

I could submit a patch to convert the build from `gem build` to use Bundler, and the `rake build` command remains the same. It would also add a `rake release` command, which could help with the gem release flow on the maintainer's end.

Refs:
- https://github.com/rubygems/rubygems/issues/191
- https://github.com/bundler/bundler/issues/2136

**Comment by miketheman** [comment]
Closing, since I don't use the library any more and I haven't heard back in just under a year.
The details are here for posterity.
