### ISSUE TITLE
Release version 0.10.0 and 0.11.0

### ISSUE THREAD

**Issue by connormurray7** [twitter/thrift_client#70]
I noticed that `thrift_client` within this repository is up to version 10. Are there any plans to release the updated `thrift_client`?

I was also able to fork the repository and build/run tests on thrift version 0.11.0, are there any plans to move up to 11 too?

**Comment by fluxusfrequency** [comment]
Hi there. Yes, we will be happy to release version 10 and move up to 11. Will get to it in the next week or so. Thanks for the patch :D

**Comment by connormurray7** [comment]
Great! thanks Ben. Let me know if I can help with anything, also if you need anyone to test version 11, I would be happy to do that.

**Comment by fluxusfrequency** [comment]
Should be all set now, published to ruby gems as well. Thanks for the help!
